services:
  gophish:
    image: gophish/gophish:0.12.1
    container_name: gophish
    ports:
      - "3333:3333"
      - "8080:8080"
    volumes:
      - ./config.json:/opt/gophish/config.json
      - gophish:/opt/gophish
    restart: always

  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    volumes:
      # - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      # - ./traefik/dynamic-config.yml:/etc/traefik/dynamic-config.yml
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

volumes:
  gophish: {}
