version: '3'

services:
  gophish:
    image: gophish/gophish:0.12.1
    container_name: gophish
    ports:
      - "3333:3333"  # Admin panel (solo accesible localmente)
    volumes:
      - ./config.json:/opt/gophish/config.json
      - gophish:/opt/gophish
    labels:
      - "traefik.enable=true"
      # Configuración para la interfaz de phishing
      - "traefik.http.routers.gophish-phish.rule=PathPrefix(`/`)"
      - "traefik.http.routers.gophish-phish.entryPoints=web"
      - "traefik.http.services.gophish-phish.loadbalancer.server.port=9000"
    restart: always
    networks:
      - web

  traefik:
    image: traefik:v2.9
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard solo accesible localmente
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=INFO"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    networks:
      - web

volumes:
  gophish: {}

networks:
  web:
    driver: bridge