services:
  gophish:
    image: gophish/gophish:0.12.1
    container_name: gophish
    ports:
      - "3333:3333"  # Admin panel
      - "9000:9000"  # Phishing site
    volumes:
      - ./config.json:/opt/gophish/config.json
      - gophish:/opt/gophish
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gophish.rule=PathPrefix(`/gophish`)"
      - "traefik.http.routers.gophish.entryPoints=web"
      - "traefik.http.services.gophish.loadbalancer.server.port=3333"
    restart: always

  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/dynamic-config.yml:/etc/traefik/dynamic-config.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

volumes:
  gophish: {}
