version: '3'

services:
  gophish:
    image: gophish/gophish:0.12.1
    container_name: gophish
    ports:
      - "3333:3333"  # Admin panel expuesto para desarrollo
      - "9000:9000"  # Phishing server
    volumes:
      - ./config.json:/opt/gophish/config.json
      - gophish:/opt/gophish
    labels:
      - "traefik.enable=true"
      # Configuración para el panel de administración
      - "traefik.http.routers.gophish-admin.rule=PathPrefix(`/gophish`)"
      - "traefik.http.routers.gophish-admin.entryPoints=web"
      - "traefik.http.services.gophish-admin.loadbalancer.server.port=3333"
      - "traefik.http.middlewares.gophish-strip.stripprefix.prefixes=/gophish"
      - "traefik.http.routers.gophish-admin.middlewares=gophish-strip"
      # Configuración para el servidor de phishing
      - "traefik.http.routers.gophish-phish.rule=PathPrefix(`/server`)"
      - "traefik.http.routers.gophish-phish.entryPoints=web"
      - "traefik.http.services.gophish-phish.loadbalancer.server.port=9000"
      - "traefik.http.middlewares.server-strip.stripprefix.prefixes=/server"
      - "traefik.http.routers.gophish-phish.middlewares=server-strip"
    restart: always
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traefik:
    image: traefik:v2.9
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"  # Dashboard expuesto para desarrollo
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--log.level=DEBUG"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  gophish: {}

networks:
  web:
    driver: bridge