services:
  gophish:
    image: gophish/gophish:0.12.1
    container_name: gophish
    ports:
      - "3333:3333" # Admin panel expuesto para desarrollo
      - "9000:9000" # Phishing server
    volumes:
      - ./config.json:/opt/gophish/config.json
      - gophish:/opt/gophish
    labels:
      - "traefik.enable=true"
      ## server app
      - "traefik.http.routers.app.rule=Host(`app.grandefensa.org`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"
      - "traefik.http.services.app.loadbalancer.server.port=3333"
      ## server phish
      - "traefik.http.routers.server.rule=Host(`server.grandefensa.org`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"
      - "traefik.http.services.server.loadbalancer.server.port=9000"
    restart: always
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: proxy:latest
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"    
    volumes:
      - "./letsencrypt:/certificates"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/conf:/etc/traefik"
    restart: always
    networks:
      - web
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  gophish: {}
  letsencrypt: {}

networks:
  web:
    driver: bridge
