# Dynamic configuration
http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "gophish_server:$apr1$isocMTyr$1I1OwxCfDr6YlVQQuSNcZ1"
    real-ip:
      forwardedHeaders:
        trustedIPs:
          - "0.0.0.0/0"

    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    acme-middleware:
      stripPrefix:
        prefixes:
          - "/.well-known/acme-challenge/"

  routers:
    traefik-dashboard:
      entryPoints:
        - "websecure"
      rule: "Host(`dashboard.grandefensa.org`)"
      service: "api@internal"
      middlewares:
        - "auth"
      tls:
        certResolver: "letsencrypt"

    app:
      entryPoints:
        - "websecure"
      rule: "Host(`app.grandefensa.org`)"
      service: "app"
      tls:
        certResolver: "letsencrypt"
    
    landing:
      entryPoints:
        - "websecure"
      rule: "Host(`landing.grandefensa.org`)"
      service: "landing"
      tls:
        certResolver: "letsencrypt"

    tracker:
      entryPoints:
        - "websecure"
      rule: "Host(`tracker.grandefensa.org`)"
      service: "tracker"
      tls:
        certResolver: "letsencrypt"

    # ACME challenge router - must accept HTTP
    acme-challenge:
      entryPoints:
        - "web"
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      service: "noop@internal"
      priority: 100

  services:
    app:
      loadBalancer:
        servers:
          - url: "http://gophish:3333"
    landing:
      loadBalancer:
        servers:
          - url: "http://gophish:9000"
    tracker:
      loadBalancer:
        middlewares:
          - "real-ip"
        servers:
          - url: "http://tracker:8000"

  # No definir rutas para los servicios app e iker_agent aquí
  # Ya que están definidos mediante etiquetas Docker
